from .many_to_many import Book
from .many_to_many import Author
from .many_to_many_self_association import Account
from .one_to_many import Order
from .one_to_many import Client
from .one_to_one import Student
from .one_to_one import Scholarship
from .one_to_one_self_association import Employee
from .standard_model import User
from .single_table_inheritance import Person
from .single_table_inheritance import NaturalPerson
from .single_table_inheritance import LegalPerson
from .joined_table_inheritance import Functionary
from .joined_table_inheritance import Coordinator
from .joined_table_inheritance import Manager